[package]
name = "bevy_reui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reui = { path = "../..", features = ["bevy"] }
bevy = "0.8"