[package]
name = "reui"
version = "0.0.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
license = "MPL-2.0"
edition = "2018"

description = "Renderer for User Interface"
homepage = "https://github.com/lain-dono/reui"
repository = "https://github.com/lain-dono/reui"
keywords = ["graphics"]
exclude = ["Cargo.lock", "examples/**/*", "tests/**/*", "target/**/*"]

[workspace]
members = [
    "examples/nvg_demo",
]

[dependencies]
wgpu = "0.5.0"
bitflags = "1.2"
palette = "0.5.0"
