[package]
name = "reui"
version = "0.0.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "examples/nvg_demo",
]

[build-dependencies]
gl_generator = "0.11"

[dependencies]
bitflags = "1.2"
smallvec = "1.3"
wgpu = "0.5.0"
