[package]
name = "reui"
version = "0.0.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
license = "MPL-2.0"
edition = "2018"

description = "Renderer for User Interface"
homepage = "https://github.com/lain-dono/reui"
repository = "https://github.com/lain-dono/reui"
keywords = ["graphics"]
exclude = ["Cargo.lock", "examples/**/*", "tests/**/*", "target/**/*"]

[workspace]
members = [
    "examples/nvg_demo",
    "examples/hello_world",
]

[dependencies]
#wgpu = "0.7.1"
wgpu = { git = 'https://github.com/gfx-rs/wgpu-rs' }

bitflags = "1.2"
palette = "0.5.0"

image = { version = "0.23.13", default-features = false, features = ["jpeg", "png"] }

winit = { version = "0.24.0", optional = true }
futures = { version = "0.3", optional = true }

glyph_brush = "0.7"

tracing = "0.1"

# text
#fnv = "1.0.7"
#owned_ttf_parser = "0.12.0"
#rustybuzz = "0.3.0"
#unicode-bidi = "0.3.4"
#unicode-segmentation = "1.6.0"
#generational-arena = "0.2.8"
#lru = { version = "0.6.3", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-executor = { version = "1.0", optional = true }
pollster = { version = "0.2", optional = true }
wgpu-subscriber = { version = "0.1", optional = true }

[features]
default = []
standalone = ["winit", "futures", "async-executor", "pollster", "wgpu-subscriber"]

#[patch.crates-io]
#wgpu = { git = 'https://github.com/gfx-rs/wgpu-rs' }
