[package]
name = "reui"
version = "0.0.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
license = "MPL-2.0"
edition = "2018"

description = "Renderer for User Interface"
homepage = "https://github.com/lain-dono/reui"
repository = "https://github.com/lain-dono/reui"
keywords = ["graphics"]
exclude = ["Cargo.lock", "examples/**/*", "tests/**/*", "target/**/*"]

[workspace]
members = [
    "examples/nvg_demo",
    "examples/hello_world",
]

[dependencies]
wgpu = "0.7.0"

bitflags = "1.2"
palette = "0.5.0"

image = { version = "0.23.13", default-features = false, features = ["jpeg", "png"] }

winit = { version = "0.24.0", optional = true }
futures = { version = "0.3", optional = true }

[features]
default = []
standalone = ["winit", "futures"]

[patch.crates-io]
wgpu = { git = 'https://github.com/gfx-rs/wgpu-rs' }
