[package]
name = "oni2d"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"

[lib]

[build-dependencies]
gl_generator = "0.11"

[dependencies]
libc = "0.2"
rlibc = "1"
bitflags = "^1.1"
env_logger = "0.5"
log = "0.4"
arrayvec = "0.5"

zerocopy = "0.2.8"

[dependencies.smallvec]
version = "^0.6"
features = ["union"]

[[example]]
name = "demo"
