[package]
name = "nvg_demo"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reui = { path = "../..", features = ["standalone"] }

tracing = "0.1"
tracing-subscriber = "0.2"