[package]
name = "nvg_demo"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reui = { path = "../.." }

wgpu = "0.5.0"
winit = "0.22.1"
futures = "0.3"
env_logger = "0.7"
palette = "0.5.0"
